axi/arbiter.v
axi/axi_full_to_half_duplex.v
axi/axi_interconnect.v
axi/priority_encoder.v
cam/cam_crop.v
cam/cam_line_buffer.v
cam/cam_picam_v2.v
cam/cam_raw_to_rgb.v
cam/cam_rgb2gray.v
cam/cam_rgb_gain.v
cam/cam_scaling.v
cam/scale_down_2x_nn.v
cam/scale_up_2x_nn.v
common/common_reset.v
common/common_apb3.v
common/common_true_dual_port_ram.v
common/common_shift_reg.v
common/common_simple_dual_port_ram.v
common/common_apb3_dualCam.v
display/dsi/display_dsi.v
display/dsi/panel_config.v
display/dsi/vga_gen.v
hw_accel/hw_accel.v
hw_accel/hw_accel_axi4.v
hw_accel/hw_accel_binary_dilation.v
hw_accel/hw_accel_binary_erosion.v
hw_accel/hw_accel_sobel_edge_detection.v
hw_accel/hw_accel_wrapper.v
hw_accel/hw_accel_line_buffer.v
hw_accel/hw_accel_dual_cam.v
hw_accel/hw_accel_wrapper_dual_cam.v
