// =============================================================================
// Generated by efx_ipmgr
// Version: 2025.1.110
// IP Version: 6.4.1
// =============================================================================

////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2025 Efinix Inc. All rights reserved.              
//
// This   document  contains  proprietary information  which   is        
// protected by  copyright. All rights  are reserved.  This notice       
// refers to original work by Efinix, Inc. which may be derivitive       
// of other work distributed under license of the authors.  In the       
// case of derivative work, nothing in this notice overrides the         
// original author's license agreement.  Where applicable, the           
// original license agreement is included in it's original               
// unmodified form immediately below this header.                        
//                                                                       
// WARRANTY DISCLAIMER.                                                  
//     THE  DESIGN, CODE, OR INFORMATION ARE PROVIDED “AS IS” AND        
//     EFINIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH               
//     RESPECT THERETO, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES,  
//     INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF          
//     MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR    
//     PURPOSE.  SOME STATES DO NOT ALLOW EXCLUSIONS OF AN IMPLIED       
//     WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO LICENSEE.           
//                                                                       
// LIMITATION OF LIABILITY.                                              
//     NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY       
//     INJURY, EFINIX SHALL NOT BE LIABLE WITH RESPECT TO ANY SUBJECT    
//     MATTER OF THIS AGREEMENT UNDER TORT, CONTRACT, STRICT LIABILITY   
//     OR ANY OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY INDIRECT,      
//     SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY    
//     CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF      
//     GOODWILL, DATA OR PROFIT, WORK STOPPAGE, OR COMPUTER FAILURE OR   
//     MALFUNCTION, OR IN ANY EVENT (II) FOR ANY AMOUNT IN EXCESS, IN    
//     THE AGGREGATE, OF THE FEE PAID BY LICENSEE TO EFINIX HEREUNDER    
//     (OR, IF THE FEE HAS BEEN WAIVED, $100), EVEN IF EFINIX SHALL HAVE 
//     BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO 
//     NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR            
//     CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT   
//     APPLY TO LICENSEE.                                                
//
////////////////////////////////////////////////////////////////////////////////

dma u_dma
(
    .clk ( clk ),
    .ctrl_reset ( ctrl_reset ),
    .reset ( reset ),
    .ctrl_clk ( ctrl_clk ),
    .ctrl_PADDR ( ctrl_PADDR ),
    .ctrl_PREADY ( ctrl_PREADY ),
    .ctrl_PENABLE ( ctrl_PENABLE ),
    .ctrl_PSEL ( ctrl_PSEL ),
    .ctrl_PWRITE ( ctrl_PWRITE ),
    .ctrl_PWDATA ( ctrl_PWDATA ),
    .ctrl_PRDATA ( ctrl_PRDATA ),
    .ctrl_PSLVERROR ( ctrl_PSLVERROR ),
    .ctrl_interrupts ( ctrl_interrupts ),
    .axi_arwvalid ( axi_arwvalid ),
    .axi_arwready ( axi_arwready ),
    .axi_arwaddr ( axi_arwaddr ),
    .axi_arwregion ( axi_arwregion ),
    .axi_arwlen ( axi_arwlen ),
    .axi_arwsize ( axi_arwsize ),
    .axi_arwburst ( axi_arwburst ),
    .axi_arwlock ( axi_arwlock ),
    .axi_arwcache ( axi_arwcache ),
    .axi_arwqos ( axi_arwqos ),
    .axi_arwprot ( axi_arwprot ),
    .axi_arwwrite ( axi_arwwrite ),
    .axi_wvalid ( axi_wvalid ),
    .axi_wready ( axi_wready ),
    .axi_wdata ( axi_wdata ),
    .axi_wstrb ( axi_wstrb ),
    .axi_wlast ( axi_wlast ),
    .axi_bvalid ( axi_bvalid ),
    .axi_bready ( axi_bready ),
    .axi_bresp ( axi_bresp ),
    .axi_rvalid ( axi_rvalid ),
    .axi_rready ( axi_rready ),
    .axi_rdata ( axi_rdata ),
    .axi_rresp ( axi_rresp ),
    .axi_rlast ( axi_rlast ),
    .dat5_o_tvalid ( dat5_o_tvalid ),
    .dat5_o_tready ( dat5_o_tready ),
    .dat5_o_tdata ( dat5_o_tdata ),
    .dat5_o_tkeep ( dat5_o_tkeep ),
    .dat5_o_tdest ( dat5_o_tdest ),
    .dat5_o_tlast ( dat5_o_tlast ),
    .dat4_o_tvalid ( dat4_o_tvalid ),
    .dat4_o_tready ( dat4_o_tready ),
    .dat4_o_tdata ( dat4_o_tdata ),
    .dat4_o_tkeep ( dat4_o_tkeep ),
    .dat4_o_tdest ( dat4_o_tdest ),
    .dat4_o_tlast ( dat4_o_tlast ),
    .dat2_o_tvalid ( dat2_o_tvalid ),
    .dat2_o_tready ( dat2_o_tready ),
    .dat2_o_tdata ( dat2_o_tdata ),
    .dat2_o_tkeep ( dat2_o_tkeep ),
    .dat2_o_tdest ( dat2_o_tdest ),
    .dat2_o_tlast ( dat2_o_tlast ),
    .io_0_descriptorUpdate ( io_0_descriptorUpdate ),
    .dat5_o_clk ( dat5_o_clk ),
    .dat5_o_reset ( dat5_o_reset ),
    .dat4_o_clk ( dat4_o_clk ),
    .dat4_o_reset ( dat4_o_reset ),
    .dat3_i_clk ( dat3_i_clk ),
    .dat3_i_reset ( dat3_i_reset ),
    .dat2_o_clk ( dat2_o_clk ),
    .dat2_o_reset ( dat2_o_reset ),
    .dat1_i_clk ( dat1_i_clk ),
    .dat1_i_reset ( dat1_i_reset ),
    .dat0_i_clk ( dat0_i_clk ),
    .dat0_i_reset ( dat0_i_reset ),
    .dat3_i_tlast ( dat3_i_tlast ),
    .dat3_i_tdata ( dat3_i_tdata ),
    .dat3_i_tvalid ( dat3_i_tvalid ),
    .dat3_i_tready ( dat3_i_tready ),
    .dat3_i_tkeep ( dat3_i_tkeep ),
    .dat3_i_tdest ( dat3_i_tdest ),
    .dat1_i_tvalid ( dat1_i_tvalid ),
    .dat1_i_tready ( dat1_i_tready ),
    .dat1_i_tdata ( dat1_i_tdata ),
    .dat1_i_tkeep ( dat1_i_tkeep ),
    .dat1_i_tdest ( dat1_i_tdest ),
    .dat1_i_tlast ( dat1_i_tlast ),
    .dat0_i_tvalid ( dat0_i_tvalid ),
    .dat0_i_tready ( dat0_i_tready ),
    .dat0_i_tdata ( dat0_i_tdata ),
    .dat0_i_tkeep ( dat0_i_tkeep ),
    .dat0_i_tdest ( dat0_i_tdest ),
    .dat0_i_tlast ( dat0_i_tlast ),
    .io_1_descriptorUpdate ( io_1_descriptorUpdate ),
    .io_2_descriptorUpdate ( io_2_descriptorUpdate ),
    .io_3_descriptorUpdate ( io_3_descriptorUpdate ),
    .io_4_descriptorUpdate ( io_4_descriptorUpdate ),
    .io_5_descriptorUpdate ( io_5_descriptorUpdate )
);
